FROM golang:1.21.6-alpine3.19 as builder

WORKDIR /src

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .
RUN go build


FROM alpine:3.19 

COPY --from=builder /src/tile-id-api /
COPY openapi.yml /
COPY swagger /swagger

ARG SERVER_PORT=8080
ENV TILE_ID_SERVER_PORT=${SERVER_PORT}
EXPOSE ${SERVER_PORT}

RUN adduser -S apiuser
USER apiuser

CMD ["/tile-id-api"]
