FROM python:3.12-alpine3.19

COPY scripts/docker/requirements.txt /
RUN pip install -r /requirements.txt

WORKDIR /tests

COPY scripts/docker/validate_http_requests.py .
CMD ["python", "validate_http_requests.py"]
