FROM golang:1.21.6-alpine3.19 as builder

WORKDIR /src

COPY tile-id-api/go.mod .
COPY tile-id-api/go.sum .
RUN go mod download

COPY tile-id-api/ .
RUN go build


FROM alpine:3.19 

COPY --from=builder /src/tile-id-api /
COPY tile-id-api/openapi.yml /
COPY tile-id-api/swagger /swagger

ARG SERVER_PORT=8080
ENV TILE_ID_SERVER_PORT=${SERVER_PORT}
EXPOSE ${SERVER_PORT}

RUN adduser -S apiuser
USER apiuser

CMD ["/tile-id-api"]
